topic_camera: "/dope/webcam/image_raw"
topic_camera_info: "/dope/webcam/camera_info"
topic_publishing: "dope"
input_is_rectified: True   # Whether the input image is rectified (strongly suggested!)
downscale_height: 500      # if the input image is larger than this, scale it down to this pixel height

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    "cracker":"package://dope/weights/cracker_60.pth",
    "gelatin":"package://dope/weights/gelatin_60.pth",
    "meat":"package://dope/weights/meat_20.pth",
    "mustard":"package://dope/weights/mustard_60.pth",
    "sugar":"package://dope/weights/sugar_60.pth",
    "TomatoSauce":"package://dope/weights/TomatoSauce.pth"
}
#Cuboid dimension in cm x,y,z
dimensions: {
    "cracker": [16.403600692749023,21.343700408935547,7.179999828338623],
    "gelatin": [8.2847003936767578, 7.0198001861572266, 6.6469998359680176],
    #"meat": [10.164673805236816,8.3542995452880859,5.7600898742675781],
    "meat": [6.7659378051757813,7.0198001861572266,6.771425724029541],
    "mustard": [9.6024150848388672,19.130100250244141,5.824894905090332],
    "TomatoSauce": [8.2847003936767578, 7.0198001861572266, 6.6469998359680176],
    "sugar": [9.267730712890625,17.625339508056641,4.5134143829345703],
}

#dimensions: {
#    "cracker": [16.403600692749023,21.343700408935547,7.179999828338623],
#    "gelatin": [6.7659378051757813,10.185500144958496,6.771425724029541],
#    "meat": [6.7659378051757813,10.185500144958496,6.771425724029541],
#    "mustard": [9.6024150848388672,19.130100250244141,5.824894905090332],
#    "TomatoSauce": #[6.7659378051757813,10.185500144958496,6.771425724029541],
#    "sugar": [6.7659378051757813,10.185500144958496,6.771425724029541],
#  
#}

class_ids: {
    "cracker": 1,
    "gelatin": 2,
    "meat":    3,
    "mustard": 4,
    "sugar":   5,
    "TomatoSauce":  6,
}

draw_colors: {
    "cracker": [13, 255, 128],  # green
    "gelatin": [255, 255, 255],  # while
    "meat": [0, 104, 255],  # blue
    "mustard": [217,12, 232],  # magenta
    "sugar": [232, 222, 12],  # yellow
    "TomatoSauce": [232, 15, 12],  # red
}

# optional: provide a transform that is applied to the pose returned by DOPE
model_transforms: {
#    "cracker": [[ 0,  0,  1,  0],
#                [ 0, -1,  0,  0],
#                [ 1,  0,  0,  0],
#                [ 0,  0,  0,  1]]
}

# optional: if you provide a mesh of the object here, a mesh marker will be
# published for visualization in RViz
meshes: {
    "TomatoSauce": "package://triple_s_util/meshes/tomato_soup/textured.obj",
    "gelatin": "package://triple_s_util/meshes/gelatin_box/textured.obj",
    "mustard": "package://triple_s_util/meshes/mustard_bottle/textured.obj",
    "cracker": "package://triple_s_util/meshes/cracker_box/textured.obj",
    "meat":  "package://triple_s_util/meshes/meat_can/textured.obj",
    "sugar":  "package://triple_s_util/meshes/sugar_box/textured.obj",
}

# optional: If the specified meshes are not in meters, provide a scale here (e.g. if the mesh is in centimeters, scale should be 0.01). default scale: 1.0.
mesh_scales: {
    "cracker": 0.01,
    "gelatin": 0.01,
    "meat":    0.01,
    "mustard": 0.01,
    "TomatoSauce":  0.01,
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1


